spring:
  datasource:
#    url: jdbc:postgresql://dpg-d69h10rh46gs73ftqre0-a.virginia-postgres.render.com:5432/mysale_3wv1_3fl9_cc4v?sslmode=require
#    username: vanny
#    password: oj6GQRNSnWYoDWomQk4w2b6wwCmNHs9B
    url: jdbc:postgresql://dpg-d6skbiggjchc73btau20-a.virginia-postgres.render.com:5432/db_lkxx?sslmode=require
    username: pws
    password: JQNbBh2vSfOSu6Bx89otd7QQfGqjv13G
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Phnom_Penh   # ✅ this line sets Cambodian timezone

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: false
telegram: 
  bot: 
    token: 8551051405:AAGgWbv84o9S1LUGWUm39M827O2T_bDzftQ 
  chat: 
    id: -1003565865573