spring:
  datasource:
<<<<<<< HEAD
    url: jdbc:postgresql://dpg-d5m6cj1r0fns73eopcag-a.virginia-postgres.render.com:5432/mysale_3wv1_3fl9?sslmode=require
    username: vanny
    password: iNDfUFZpOKSj8Ycyz1GcKULqMDtopAxI


#    url: jdbc:postgresql://dpg-d5fpno4hg0os73dtccng-a.virginia-postgres.render.com:5432/invoiceing_0dlp?sslmode=require
#    username: invoiceing_0dlp_user
#    password: xPbJx7OzY3QQQAudjtEiePPIYfbJnhNt


=======
  
  
    url: jdbc:postgresql://dpg-d5m6cj1r0fns73eopcag-a.virginia-postgres.render.com:5432/mysale_3wv1_3fl9?sslmode=require
    username: vanny
    password: iNDfUFZpOKSj8Ycyz1GcKULqMDtopAxI
    
#    url: jdbc:postgresql://dpg-d69h10rh46gs73ftqre0-a.virginia-postgres.render.com:5432/mysale_3wv1_3fl9_cc4v?sslmode=require
#    username: vanny
#    password: oj6GQRNSnWYoDWomQk4w2b6wwCmNHs9B
>>>>>>> Sale_listv2

    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Phnom_Penh   # ✅ this line sets Cambodian timezone

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: false
telegram: 
  bot: 
    token: 8551051405:AAGgWbv84o9S1LUGWUm39M827O2T_bDzftQ 
  chat: 
    id: -1003565865573