spring:
  datasource:
    url: jdbc:postgresql://dpg-d5m6cj1r0fns73eopcag-a.virginia-postgres.render.com:5432/mysale_3wv1_3fl9?sslmode=require
    username: vanny
    password: iNDfUFZpOKSj8Ycyz1GcKULqMDtopAxI
    
#RealData
#    url: jdbc:postgresql://dpg-d5n0p6e3jp1c73adlas0-a.virginia-postgres.render.com:5432/mysale_133d?sslmode=require
#    username: vanny
#    password: 2AIIk7UrMvdsuW4r3hMeQ83TcMIxdMrZ


    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Phnom_Penh   # ✅ this line sets Cambodian timezone

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: false
telegram: 
  bot: 
    token: 8551051405:AAGgWbv84o9S1LUGWUm39M827O2T_bDzftQ 
  chat: 
    id: -1003565865573